# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackpy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-id']},
        ),
    ]
