# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackpy_app', '0002_auto_20180216_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackpy_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hackpy_app.User'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='userpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='hackpy_app.UserPost'),
        ),
    ]
