# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackpy_app', '0009_auto_20180216_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='hackpy_app.User')),
                ('userpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='hackpy_app.UserPost')),
            ],
        ),
    ]
