# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackpy_app', '0013_auto_20180217_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='postvote',
            name='userpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='hackpy_app.UserPost'),
        ),
    ]
