# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackpy_app', '0014_auto_20180217_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set([('user', 'userpost')]),
        ),
    ]
