# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackpy_app', '0016_auto_20180221_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='post_link_host',
            new_name='post_host',
        ),
    ]
