# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackpy_app', '0018_auto_20180221_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_link',
            field=models.URLField(max_length=500),
        ),
    ]
